version: "3.8"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - /Users/admin/Desktop/streaming/grafana_data/grafana:/var/lib/grafana
